services:
  db:
    image: postgres:18
    container_name: pare-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pare-api
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"
      MediatR__LicenseKey: ${MEDIATR_LICENSE_KEY}
      Jwt__SecretKey: ${JWT_SECRET_KEY}
      ExchangeRate__ApiKey: ${EXCHANGE_RATE_API_KEY}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pare-frontend
    depends_on:
      - api

  caddy:
    image: caddy:latest
    container_name: pare-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api
      - frontend

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
