x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  api:
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      Email__Provider: Resend
      Resend__ApiKey: ${RESEND_API_KEY}
      Resend__EmailSender: ${RESEND_EMAIL_SENDER}
      Hangfire__Login: ${HANGFIRE_LOGIN}
      Hangfire__Password: ${HANGFIRE_PASSWORD}
    ports:
      - "127.0.0.1:8080:8080"
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 600M
    logging: *default-logging
    restart: unless-stopped

  frontend:
    ports:
      - "127.0.0.1:3000:80"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
    logging: *default-logging
    restart: unless-stopped

  db:
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 400M
    logging: *default-logging
    restart: unless-stopped

  caddy:
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 200M
    logging: *default-logging
